import type { Metadata } from "next";
import { Montserrat, Lemonada, Caveat, Rubik, Cairo } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/components/layouts/Aos";
import { AuthInitializer } from "@/components/auth/AuthInitializer";
import { UserPortfolioProvider } from "@/lib/context/UserPortfolioContext";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["400"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
  weight: ["400", "600"],
});
const lemonada = Lemonada({
  variable: "--font-lemonada",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/Circle.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" data-scroll-behavior="smooth">
      <body
        className={`${montserrat.variable} ${rubik.variable} ${lemonada.variable} ${cairo.variable} ${caveat.variable}`}
        suppressHydrationWarning
      >
        <AOSInit />
        <AuthInitializer />
        <UserPortfolioProvider>{children}</UserPortfolioProvider>
      </body>
    </html>
  );
}
