import type { Metadata } from "next";
import { Montserrat, Lobster, Inconsolata, Tagesschrift, Caveat } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/styles/Aos";
import { AuthProvider } from "@/context/AuthContext";
import { RecoveryPasswordProvider } from "@/context/RecoveryPasswordContext";
import { PublishedDesignProvider } from "@/context/PublishedDesignContext";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const lobster = Lobster({
  variable: "--font-lobster",
  subsets: ["latin"],
  weight: ["400"],
});

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const tagesschrift = Tagesschrift({
  variable: "--font-tagesschrift",
  subsets: ["latin"],
  weight: ["400"],
});
const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" data-scroll-behavior="smooth">
      <AOSInit />
      <body
        className={`${montserrat.variable} ${lobster.variable} ${inconsolata.variable} ${tagesschrift.variable} ${caveat.variable}`}
      >
        <AuthProvider>
          <RecoveryPasswordProvider>
            <PublishedDesignProvider>{children}</PublishedDesignProvider>
          </RecoveryPasswordProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
