import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/styles/Aos";
import { AuthProvider } from "@/context/AuthContext";
import { RecoveryPasswordProvider } from "@/context/RecoveryPasswordContext";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" data-scroll-behavior="smooth">
      <AOSInit />
      <body className={`${montserrat.variable}`}>
        <AuthProvider>
          <RecoveryPasswordProvider>{children}</RecoveryPasswordProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
